The Cat Api Service & The Dog Api Service
NetsBlox/services pull request #88
Opened 2023-01-27 18:24 UTC by ebiwonjumit

Created services using https://thedogapi.com/ and https://thecatapi.com/

2023-01-27 18:24 UTC, ebiwonjumit commented
PLEASE DONT REVIEW YET. STILL NEEDING API CONSUMER

2023-01-27 23:33 UTC, ebiwonjumit commented
Good to review!

2023-01-30 17:49 UTC, brollb requested changes
Nice work, @ebiwonjumit! I added some comments below. A couple bigger comments:
- [ ] Can you add tests for the interface? These are used to ensure we don't break backwards compatibility with any existing NetsBlox projects. Examples can be found in the `test/procedures` directory.
- [ ] Add an RPC for querying the list of all supported breeds. This is useful to help users explore the RPCs before digging into the docs :)

2023-01-30 17:49 UTC, brollb commented on src/procedures/the-cat-api/the-cat-api.js
> +TheCatApi.getRandomCatImage = async function(catBreeds = ''){
Isn't `catBreeds` a single breed? I was a little thrown off here initially wondering if it was a comma-separated list or something.

2023-01-30 17:49 UTC, brollb commented on src/procedures/the-dog-api/the-dog-api.js
> +const axios = require('axios');
unused import

2023-01-30 17:49 UTC, brollb commented on src/procedures/the-dog-api/the-dog-api.js
> +const {dogTypes} = require('./types');
rename (see earlier comment)

2023-01-30 17:49 UTC, brollb commented on src/procedures/the-dog-api/the-dog-api.js
> + * @param {BreedsOfDogs=} dogBreeds The list of all possible Dog Breeds filterable.
Same comment about naming enums as in the cat api service

2023-01-30 17:49 UTC, brollb commented on src/procedures/the-dog-api/types.js
> +        name: 'BreedsOfDogs',
See earlier comment about naming enum types

2023-01-30 17:49 UTC, brollb commented on src/procedures/utils/api-key.js
> +    'THE_CAT_API_KEY'
This doesn't need to be set (unless there is a reason it needs this env name). This feature was initially added for backwards compatibility; the default should be good for most cases.

2023-02-03 17:36 UTC, closed without merging